"""
Metadatos del diccionario de datos GEODIS Colombia (generado automaticamente).
Fuente: GEODIS_Colombia_Diccionario_Datos.csv
NO editar a mano: regenerar con backend/scripts/_gen_field_metadata.py
"""

FIELDS = [
    {
        "variable": "ID_Viaje",
        "column": "id_viaje",
        "tipo_dato": "Identificador",
        "sql_type": "String",
        "unidad": "Texto (código)",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Identificador único del viaje/envío, formato GDS-AAAA-NNNNNN.",
        "grupo": "identificacion_temporal",
    },
    {
        "variable": "Fecha",
        "column": "fecha",
        "tipo_dato": "Numérica (fecha)",
        "sql_type": "Date",
        "unidad": "AAAA-MM-DD",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Fecha en que se despacha el viaje.",
        "grupo": "identificacion_temporal",
    },
    {
        "variable": "Día_Semana",
        "column": "dia_semana",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Día de la semana correspondiente a la fecha del viaje.",
        "grupo": "otro",
    },
    {
        "variable": "Mes",
        "column": "mes",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Mes calendario del viaje.",
        "grupo": "identificacion_temporal",
    },
    {
        "variable": "Trimestre",
        "column": "trimestre",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Entero (1-4)",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Trimestre del año calendario.",
        "grupo": "identificacion_temporal",
    },
    {
        "variable": "Año",
        "column": "ano",
        "tipo_dato": "Numérica (discreta)",
        "sql_type": "Integer",
        "unidad": "Año (AAAA)",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Año calendario del viaje (2023-2025).",
        "grupo": "otro",
    },
    {
        "variable": "Departamento_Origen",
        "column": "departamento_origen",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "DANE / IGAC (división político-administrativa)",
        "descripcion": "Departamento colombiano donde se origina el viaje.",
        "grupo": "geografia",
    },
    {
        "variable": "Municipio_Origen",
        "column": "municipio_origen",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "DANE / IGAC (división político-administrativa)",
        "descripcion": "Municipio o ciudad nodo de origen (incluye los puertos de Buenaventura, Cartagena, Barranquilla y Santa Marta).",
        "grupo": "geografia",
    },
    {
        "variable": "Departamento_Destino",
        "column": "departamento_destino",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "DANE / IGAC (división político-administrativa)",
        "descripcion": "Departamento colombiano de destino del viaje.",
        "grupo": "geografia",
    },
    {
        "variable": "Municipio_Destino",
        "column": "municipio_destino",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "DANE / IGAC (división político-administrativa)",
        "descripcion": "Municipio o ciudad nodo de destino.",
        "grupo": "geografia",
    },
    {
        "variable": "Corredor_Logístico",
        "column": "corredor_logistico",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "ANI / Mintransporte (red de corredores logísticos)",
        "descripcion": "Nombre del corredor origen-destino (par de ciudades nodo).",
        "grupo": "geografia",
    },
    {
        "variable": "Ruta_Principal",
        "column": "ruta_principal",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "INVÍAS / ANI (red vial nacional)",
        "descripcion": "Vía troncal o corredor físico principal utilizado (p. ej. Ruta del Sol, Autopista al Mar, Panamericana).",
        "grupo": "geografia",
    },
    {
        "variable": "Tipo_Transporte",
        "column": "tipo_transporte",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto (Carretero/Marítimo/Aéreo)",
        "fuente": "Mintransporte / DIMAR / Aerocivil",
        "descripcion": "Modo de transporte utilizado en el viaje.",
        "grupo": "operacion_carga",
    },
    {
        "variable": "Tipo_Vehículo",
        "column": "tipo_vehiculo",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "Mintransporte (RNDC) / DIMAR / Aerocivil",
        "descripcion": "Tipo de vehículo, buque o aeronave asociado al modo de transporte.",
        "grupo": "otro",
    },
    {
        "variable": "Tipo_Carga",
        "column": "tipo_carga",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "Interno GEODIS (simulado, sectores declarados por GEODIS)",
        "descripcion": "Categoría de la mercancía transportada.",
        "grupo": "operacion_carga",
    },
    {
        "variable": "Sector_Cliente",
        "column": "sector_cliente",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "Interno GEODIS (simulado, sectores declarados por GEODIS)",
        "descripcion": "Sector económico del cliente (tecnología, retail, consumo masivo, industrial, automotriz, salud).",
        "grupo": "operacion_carga",
    },
    {
        "variable": "Peso_Toneladas",
        "column": "peso_toneladas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Toneladas",
        "fuente": "Superintendencia de Transporte (límites de peso por eje)",
        "descripcion": "Peso bruto de la carga transportada en el viaje.",
        "grupo": "operacion_carga",
    },
    {
        "variable": "Volumen_m3",
        "column": "volumen_m3",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Metros cúbicos (m³)",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Volumen de la carga transportada.",
        "grupo": "operacion_carga",
    },
    {
        "variable": "Distancia_Km",
        "column": "distancia_km",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Kilómetros",
        "fuente": "INVÍAS / ANI / SICE-TAC (distancias de referencia de la red vial)",
        "descripcion": "Distancia recorrida entre el nodo de origen y el de destino.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Tiempo_Programado_Horas",
        "column": "tiempo_programado_horas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Horas",
        "fuente": "GEODIS / SICE-TAC (tiempos de tránsito de referencia)",
        "descripcion": "Tiempo de tránsito comprometido (SLA) para el viaje, según distancia, modo y tipo de operación.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Tiempo_Entrega_Real_Horas",
        "column": "tiempo_entrega_real_horas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Horas",
        "fuente": "Interno GEODIS (simulado, TMS/GPS)",
        "descripcion": "Tiempo total real transcurrido entre el despacho y la entrega.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Velocidad_Promedio_Kmh",
        "column": "velocidad_promedio_kmh",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Km/h",
        "fuente": "SICE-TAC / Mintransporte",
        "descripcion": "Velocidad promedio efectiva del viaje según el modo de transporte.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Tiempo_Espera_Horas",
        "column": "tiempo_espera_horas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Horas",
        "fuente": "Interno GEODIS (simulado, TMS/GPS)",
        "descripcion": "Tiempo adicional de espera no planeado (colas, congestión, trámites) durante el viaje.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Consumo_Combustible_Galones",
        "column": "consumo_combustible_galones",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Galones",
        "fuente": "Mintransporte / UPME (rendimientos de referencia)",
        "descripcion": "Combustible consumido en el viaje (diésel para carretero/marítimo, equivalente para aéreo).",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Costo_Transporte_COP",
        "column": "costo_transporte_cop",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP (pesos colombianos)",
        "fuente": "Interno GEODIS (simulado, tarifas relativas por distancia/modo/vehículo)",
        "descripcion": "Costo total de transporte del viaje (flete).",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Costo_Peajes_COP",
        "column": "costo_peajes_cop",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP",
        "fuente": "ANI (tarifas de peaje por categoría vehicular)",
        "descripcion": "Costo estimado de peajes para viajes por carretera.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Disponibilidad_Flota_Pct",
        "column": "disponibilidad_flota_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje (%)",
        "fuente": "Interno GEODIS (simulado, KPI de flota)",
        "descripcion": "Porcentaje de la flota de transporte disponible al momento del despacho.",
        "grupo": "flota",
    },
    {
        "variable": "Utilización_Flota_Pct",
        "column": "utilizacion_flota_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje (%)",
        "fuente": "Interno GEODIS (simulado, KPI de flota)",
        "descripcion": "Porcentaje de utilización/ocupación de la flota disponible.",
        "grupo": "otro",
    },
    {
        "variable": "Estado_Vía",
        "column": "estado_via",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Bueno < Regular < Malo < Crítico)",
        "fuente": "INVÍAS (estado de la red vial nacional)",
        "descripcion": "Estado general de la vía principal utilizada en el viaje.",
        "grupo": "otro",
    },
    {
        "variable": "Índice_Deterioro_Vial",
        "column": "indice_deterioro_vial",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100 (mayor = peor estado)",
        "fuente": "INVÍAS (índice de estado de la red vial)",
        "descripcion": "Índice compuesto de deterioro de la infraestructura vial del corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Número_Cierres_Viales",
        "column": "numero_cierres_viales",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "INVÍAS (reportes de cierres viales)",
        "descripcion": "Número de cierres viales registrados en el corredor durante el viaje.",
        "grupo": "otro",
    },
    {
        "variable": "Número_Bloqueos_Carretera",
        "column": "numero_bloqueos_carretera",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "INVÍAS / Policía Nacional (reportes de bloqueos)",
        "descripcion": "Número de bloqueos de vía (protestas, derrumbes, etc.) que afectaron el corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Índice_Bloqueos",
        "column": "indice_bloqueos",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100",
        "fuente": "INVÍAS / Policía Nacional",
        "descripcion": "Índice compuesto de afectación por bloqueos y cierres viales.",
        "grupo": "otro",
    },
    {
        "variable": "Obras_Viales_Activas",
        "column": "obras_viales_activas",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de obras",
        "fuente": "INVÍAS (plan de obras activas)",
        "descripcion": "Número de obras viales activas en el corredor.",
        "grupo": "infraestructura_vial",
    },
    {
        "variable": "Restricciones_Peso",
        "column": "restricciones_peso",
        "tipo_dato": "Binaria",
        "sql_type": "Integer",
        "unidad": "0 = No, 1 = Sí",
        "fuente": "Mintransporte / Superintendencia de Transporte",
        "descripcion": "Indica si aplicaron restricciones de peso al vehículo en el viaje.",
        "grupo": "infraestructura_vial",
    },
    {
        "variable": "Restricciones_Horarias",
        "column": "restricciones_horarias",
        "tipo_dato": "Binaria",
        "sql_type": "Integer",
        "unidad": "0 = No, 1 = Sí",
        "fuente": "Mintransporte (pico y placa de carga, restricciones urbanas)",
        "descripcion": "Indica si aplicaron restricciones horarias de circulación.",
        "grupo": "infraestructura_vial",
    },
    {
        "variable": "Índice_Seguridad",
        "column": "indice_seguridad",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100 (mayor = más seguro)",
        "fuente": "Policía Nacional / Ministerio de Defensa",
        "descripcion": "Índice compuesto de seguridad vial y de carga en el corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Riesgo_Hurto_Carga",
        "column": "riesgo_hurto_carga",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Bajo < Medio < Alto)",
        "fuente": "Policía Nacional (estadísticas de hurto a mercancías)",
        "descripcion": "Nivel de riesgo de hurto de carga en el corredor y tipo de mercancía.",
        "grupo": "seguridad",
    },
    {
        "variable": "Número_Eventos_Seguridad",
        "column": "numero_eventos_seguridad",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "Policía Nacional / Ministerio de Defensa",
        "descripcion": "Número de eventos de seguridad (hurtos, retenes ilegales, incidentes) reportados.",
        "grupo": "otro",
    },
    {
        "variable": "Presencia_Grupos_Armados",
        "column": "presencia_grupos_armados",
        "tipo_dato": "Binaria",
        "sql_type": "Integer",
        "unidad": "0 = No, 1 = Sí",
        "fuente": "Ministerio de Defensa (zonas de influencia de grupos armados)",
        "descripcion": "Indica presencia reportada de grupos armados ilegales en la zona del corredor.",
        "grupo": "seguridad",
    },
    {
        "variable": "Índice_Orden_Público",
        "column": "indice_orden_publico",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100 (mayor = mejor orden público)",
        "fuente": "Ministerio de Defensa / Policía Nacional",
        "descripcion": "Índice compuesto de orden público de la región del corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Riesgo_Extorsión",
        "column": "riesgo_extorsion",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Bajo < Medio < Alto)",
        "fuente": "Policía Nacional / Ministerio de Defensa",
        "descripcion": "Nivel de riesgo de extorsión asociado al corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Riesgo_Vandalismo",
        "column": "riesgo_vandalismo",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Bajo < Medio < Alto)",
        "fuente": "Policía Nacional",
        "descripcion": "Nivel de riesgo de vandalismo sobre la carga o el vehículo.",
        "grupo": "seguridad",
    },
    {
        "variable": "Riesgo_Saqueo",
        "column": "riesgo_saqueo",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Bajo < Medio < Alto)",
        "fuente": "Policía Nacional / UNGRD",
        "descripcion": "Nivel de riesgo de saqueo de la carga, asociado a bloqueos y protestas.",
        "grupo": "seguridad",
    },
    {
        "variable": "Número_Paros",
        "column": "numero_paros",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "Ministerio del Interior / Policía Nacional (registro de paros)",
        "descripcion": "Número de paros (nacionales, regionales o gremiales) activos que afectaron el viaje.",
        "grupo": "otro",
    },
    {
        "variable": "Índice_Protestas",
        "column": "indice_protestas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100",
        "fuente": "Ministerio del Interior / Policía Nacional",
        "descripcion": "Índice de intensidad de protestas y movilizaciones sociales en el corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Manifestaciones",
        "column": "manifestaciones",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "Policía Nacional (registro de manifestaciones públicas)",
        "descripcion": "Número de manifestaciones públicas registradas durante el viaje.",
        "grupo": "orden_social",
    },
    {
        "variable": "Huelgas",
        "column": "huelgas",
        "tipo_dato": "Binaria",
        "sql_type": "Integer",
        "unidad": "0 = No, 1 = Sí",
        "fuente": "Ministerio del Trabajo / Ministerio del Interior",
        "descripcion": "Indica si hubo una huelga activa que afectó la operación.",
        "grupo": "orden_social",
    },
    {
        "variable": "Bloqueos_Sociales",
        "column": "bloqueos_sociales",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "UNGRD / Policía Nacional",
        "descripcion": "Número de bloqueos de origen social (no vial-estructural) en el corredor.",
        "grupo": "orden_social",
    },
    {
        "variable": "Temperatura_C",
        "column": "temperatura_c",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Grados Celsius (°C)",
        "fuente": "IDEAM (registros climatológicos)",
        "descripcion": "Temperatura promedio registrada en el corredor durante el viaje.",
        "grupo": "clima",
    },
    {
        "variable": "Precipitación_mm",
        "column": "precipitacion_mm",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Milímetros (mm)",
        "fuente": "IDEAM (registros de precipitación)",
        "descripcion": "Precipitación acumulada estimada en el día del viaje.",
        "grupo": "otro",
    },
    {
        "variable": "Humedad_Pct",
        "column": "humedad_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje (%)",
        "fuente": "IDEAM",
        "descripcion": "Humedad relativa promedio registrada en el corredor.",
        "grupo": "clima",
    },
    {
        "variable": "Velocidad_Viento_Kmh",
        "column": "velocidad_viento_kmh",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Km/h",
        "fuente": "IDEAM",
        "descripcion": "Velocidad promedio del viento registrada en el corredor.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Alerta_IDEAM",
        "column": "alerta_ideam",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Ninguna < Amarilla < Naranja < Roja)",
        "fuente": "IDEAM (sistema de alertas tempranas)",
        "descripcion": "Nivel de alerta meteorológica vigente durante el viaje.",
        "grupo": "clima",
    },
    {
        "variable": "Fenómeno_Climático",
        "column": "fenomeno_climatico",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "IDEAM (boletines de fenómenos climáticos y ENSO)",
        "descripcion": "Fenómeno climático predominante (El Niño, La Niña, vaguada, ola de calor, etc.).",
        "grupo": "otro",
    },
    {
        "variable": "Número_Inundaciones",
        "column": "numero_inundaciones",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "UNGRD (registro de emergencias)",
        "descripcion": "Número de inundaciones reportadas en la zona del corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Índice_Inundaciones",
        "column": "indice_inundaciones",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100",
        "fuente": "UNGRD / IDEAM",
        "descripcion": "Índice de afectación por inundaciones en el corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Número_Deslizamientos",
        "column": "numero_deslizamientos",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "UNGRD (registro de emergencias)",
        "descripcion": "Número de deslizamientos de tierra reportados en el corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Índice_Deslizamientos",
        "column": "indice_deslizamientos",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100",
        "fuente": "UNGRD",
        "descripcion": "Índice de afectación por deslizamientos en el corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Número_Derrumbes",
        "column": "numero_derrumbes",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "UNGRD / INVÍAS (registro de emergencias viales)",
        "descripcion": "Número de derrumbes que afectaron la vía utilizada.",
        "grupo": "otro",
    },
    {
        "variable": "Índice_Derrumbes",
        "column": "indice_derrumbes",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100",
        "fuente": "UNGRD / INVÍAS",
        "descripcion": "Índice de afectación por derrumbes en el corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Número_Incendios_Forestales",
        "column": "numero_incendios_forestales",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "UNGRD / IDEAM (registro de incendios de cobertura vegetal)",
        "descripcion": "Número de incendios forestales activos cerca del corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Índice_Incendios",
        "column": "indice_incendios",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100",
        "fuente": "UNGRD / IDEAM",
        "descripcion": "Índice de afectación por incendios forestales.",
        "grupo": "otro",
    },
    {
        "variable": "Riesgo_Geológico",
        "column": "riesgo_geologico",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Bajo < Medio < Alto)",
        "fuente": "UNGRD / Servicio Geológico Colombiano",
        "descripcion": "Nivel de riesgo geológico (deslizamientos/derrumbes) del corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Riesgo_Hidrológico",
        "column": "riesgo_hidrologico",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Bajo < Medio < Alto)",
        "fuente": "UNGRD / IDEAM",
        "descripcion": "Nivel de riesgo hidrológico (inundaciones) del corredor.",
        "grupo": "otro",
    },
    {
        "variable": "Número_Accidentes",
        "column": "numero_accidentes",
        "tipo_dato": "Numérica discreta (conteo)",
        "sql_type": "Integer",
        "unidad": "Número de eventos",
        "fuente": "Policía Nacional / ANSV (Agencia Nacional de Seguridad Vial)",
        "descripcion": "Número de accidentes de tránsito registrados durante el viaje.",
        "grupo": "otro",
    },
    {
        "variable": "Intensidad_Incidente",
        "column": "intensidad_incidente",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Ninguno < Leve < Moderado < Grave)",
        "fuente": "Policía Nacional / ANSV",
        "descripcion": "Severidad del incidente vial más relevante del viaje.",
        "grupo": "incidentes",
    },
    {
        "variable": "Duración_Incidente_Horas",
        "column": "duracion_incidente_horas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Horas",
        "fuente": "Policía Nacional / ANSV",
        "descripcion": "Duración estimada del incidente vial reportado.",
        "grupo": "otro",
    },
    {
        "variable": "Tiempo_Cierre_Vía_Horas",
        "column": "tiempo_cierre_via_horas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Horas",
        "fuente": "INVÍAS / Policía Nacional",
        "descripcion": "Tiempo total que la vía permaneció cerrada por incidentes o bloqueos.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Precio_Diésel_COP_Gal",
        "column": "precio_diesel_cop_gal",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP por galón",
        "fuente": "Mintransporte / DANE (precios de combustibles)",
        "descripcion": "Precio de referencia del ACPM/diésel vigente en la fecha del viaje.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Precio_Gasolina_COP_Gal",
        "column": "precio_gasolina_cop_gal",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP por galón",
        "fuente": "Mintransporte / DANE",
        "descripcion": "Precio de referencia de la gasolina corriente vigente en la fecha del viaje.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "IPC",
        "column": "ipc",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice (base 100 = ene-2023)",
        "fuente": "DANE (Índice de Precios al Consumidor)",
        "descripcion": "Índice de precios al consumidor vigente en el mes del viaje.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "TRM_COP_USD",
        "column": "trm_cop_usd",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP por USD",
        "fuente": "Banco de la República / DANE",
        "descripcion": "Tasa representativa del mercado (TRM) vigente en la fecha del viaje.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Inflación_Pct",
        "column": "inflacion_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje anual (%)",
        "fuente": "DANE",
        "descripcion": "Inflación anual (variación interanual del IPC) vigente en el mes del viaje.",
        "grupo": "otro",
    },
    {
        "variable": "Precio_Peajes_Promedio_COP",
        "column": "precio_peajes_promedio_cop",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP por peaje",
        "fuente": "ANI (tarifas de peaje por categoría vehicular)",
        "descripcion": "Tarifa promedio de peaje aplicable según categoría vehicular.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Índice_Abastecimiento",
        "column": "indice_abastecimiento",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Índice 0-100",
        "fuente": "SIPSA / Corabastos (DANE)",
        "descripcion": "Índice de abastecimiento de la cadena de suministro relacionada con la carga.",
        "grupo": "otro",
    },
    {
        "variable": "Nivel_Inventario_Pct",
        "column": "nivel_inventario_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje (%) de capacidad",
        "fuente": "Interno GEODIS / SIPSA-Corabastos (simulado)",
        "descripcion": "Nivel de inventario disponible en el nodo de origen o bodega asociada.",
        "grupo": "demanda_inventario",
    },
    {
        "variable": "Demanda_Unidades",
        "column": "demanda_unidades",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Unidades",
        "fuente": "SIPSA / Corabastos / Interno GEODIS (simulado)",
        "descripcion": "Demanda real estimada para el tipo de carga y periodo del viaje.",
        "grupo": "demanda_inventario",
    },
    {
        "variable": "Demanda_Pronosticada_Unidades",
        "column": "demanda_pronosticada_unidades",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Unidades",
        "fuente": "Interno GEODIS (simulado, pronóstico de demanda)",
        "descripcion": "Demanda pronosticada previa al viaje, con error de pronóstico respecto a la demanda real.",
        "grupo": "demanda_inventario",
    },
    {
        "variable": "Prioridad_Cliente",
        "column": "prioridad_cliente",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Estándar < Alta < Crítica/Estratégico)",
        "fuente": "Interno GEODIS (segmentación comercial de clientes)",
        "descripcion": "Nivel de prioridad comercial y de servicio asignado al cliente.",
        "grupo": "servicio_cliente",
    },
    {
        "variable": "OTIF",
        "column": "otif",
        "tipo_dato": "Binaria",
        "sql_type": "Integer",
        "unidad": "0 = No cumplido, 1 = Cumplido",
        "fuente": "Interno GEODIS (KPI On Time In Full)",
        "descripcion": "Indica si el viaje cumplió la entrega a tiempo y completa (OTIF) dentro de la tolerancia SLA.",
        "grupo": "servicio_cliente",
    },
    {
        "variable": "Fill_Rate_Pct",
        "column": "fill_rate_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje (%)",
        "fuente": "Interno GEODIS (KPI de completitud de pedido)",
        "descripcion": "Porcentaje de la carga solicitada que fue efectivamente despachada.",
        "grupo": "servicio_cliente",
    },
    {
        "variable": "Nivel_Servicio_Pct",
        "column": "nivel_servicio_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje (%)",
        "fuente": "Interno GEODIS (KPI compuesto de nivel de servicio)",
        "descripcion": "Indicador compuesto de nivel de servicio (OTIF, fill rate y seguridad).",
        "grupo": "servicio_cliente",
    },
    {
        "variable": "Tiempo_Almacenamiento_Horas",
        "column": "tiempo_almacenamiento_horas",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Horas",
        "fuente": "Interno GEODIS (Contract Logistics, simulado)",
        "descripcion": "Tiempo que la carga permaneció almacenada en bodega antes de su despacho final.",
        "grupo": "tiempos_transito",
    },
    {
        "variable": "Cross_Docking",
        "column": "cross_docking",
        "tipo_dato": "Binaria",
        "sql_type": "Integer",
        "unidad": "0 = No, 1 = Sí",
        "fuente": "Interno GEODIS (operación de cross-docking)",
        "descripcion": "Indica si el viaje utilizó una operación de cross-docking.",
        "grupo": "almacenamiento",
    },
    {
        "variable": "Tipo_Bodega",
        "column": "tipo_bodega",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "Interno GEODIS (Contract Logistics, simulado)",
        "descripcion": "Tipo de bodega asociada al almacenamiento de la carga.",
        "grupo": "almacenamiento",
    },
    {
        "variable": "Capacidad_Bodega_m3",
        "column": "capacidad_bodega_m3",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Metros cúbicos (m³)",
        "fuente": "Interno GEODIS (simulado)",
        "descripcion": "Capacidad instalada de la bodega o nodo de almacenamiento asociado.",
        "grupo": "almacenamiento",
    },
    {
        "variable": "Utilización_Bodega_Pct",
        "column": "utilizacion_bodega_pct",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "Porcentaje (%)",
        "fuente": "Interno GEODIS (KPI de bodega)",
        "descripcion": "Porcentaje de utilización de la capacidad de bodega disponible.",
        "grupo": "otro",
    },
    {
        "variable": "Aseguradora",
        "column": "aseguradora",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto",
        "fuente": "Mercado asegurador colombiano de carga (no es fuente pública oficial; supuesto de mercado)",
        "descripcion": "Compañía aseguradora que ampara la carga transportada en el viaje.",
        "grupo": "seguros",
    },
    {
        "variable": "Tipo_Cobertura_Seguro",
        "column": "tipo_cobertura_seguro",
        "tipo_dato": "Ordinal",
        "sql_type": "String",
        "unidad": "Categoría (Básica < RC Transportador < Todo Riesgo)",
        "fuente": "Supuesto de mercado (pólizas de transporte de mercancías en Colombia)",
        "descripcion": "Nivel de cobertura de la póliza de seguro de carga contratada para el viaje.",
        "grupo": "seguros",
    },
    {
        "variable": "Valor_Asegurado_COP",
        "column": "valor_asegurado_cop",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP",
        "fuente": "Supuesto de mercado, derivado de Peso_Toneladas y Tipo_Carga",
        "descripcion": "Valor asegurado de la mercancía transportada en el viaje.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Prima_Seguro_COP",
        "column": "prima_seguro_cop",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP",
        "fuente": "Supuesto de mercado (tasas típicas de seguro de transporte de mercancías)",
        "descripcion": "Costo de la prima del seguro para el viaje, en función del valor asegurado, la cobertura y el riesgo del corredor.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Deducible_COP",
        "column": "deducible_cop",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP",
        "fuente": "Supuesto de mercado (condicionado por el tipo de cobertura)",
        "descripcion": "Monto deducible a cargo de GEODIS/cliente en caso de siniestro.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Siniestro",
        "column": "siniestro",
        "tipo_dato": "Binaria",
        "sql_type": "Integer",
        "unidad": "0 = No, 1 = Sí",
        "fuente": "Supuesto de mercado, ligado a Riesgo_Hurto_Carga, Riesgo_Saqueo y Número_Accidentes",
        "descripcion": "Indica si se presentó un siniestro (pérdida, daño o hurto) de la carga durante el viaje.",
        "grupo": "seguros",
    },
    {
        "variable": "Valor_Siniestro_COP",
        "column": "valor_siniestro_cop",
        "tipo_dato": "Numérica continua",
        "sql_type": "Float",
        "unidad": "COP",
        "fuente": "Supuesto de mercado (severidad del siniestro sobre el valor asegurado)",
        "descripcion": "Valor reclamado del siniestro; 0 si no hubo siniestro.",
        "grupo": "economico_financiero",
    },
    {
        "variable": "Estado_Reclamación",
        "column": "estado_reclamacion",
        "tipo_dato": "Categórica",
        "sql_type": "String",
        "unidad": "Texto (No Aplica/Pagada/En Trámite/Rechazada)",
        "fuente": "Supuesto de mercado (proceso típico de reclamación de seguros)",
        "descripcion": "Estado de la reclamación ante la aseguradora; 'No Aplica' si no hubo siniestro.",
        "grupo": "otro",
    },
    {
        "variable": "LeadTime_Real_Dias",
        "column": "leadtime_real_dias",
        "tipo_dato": "Numérica continua (variable objetivo)",
        "sql_type": "Float",
        "unidad": "Días",
        "fuente": "Interno GEODIS (KPI Lead Time)",
        "descripcion": "Tiempo total real de entrega del viaje, en días, desde el despacho hasta la entrega. Variable objetivo del modelo predictivo: depende de distancia, estado de la vía, congestión, bloqueos, paros, seguridad, clima, derrumbes, inundaciones, incendios forestales, disponibilidad de flota, accidentes, tiempo de espera, nivel de inventario y tipo de transporte, con relaciones no lineales y ruido operativo.",
        "grupo": "objetivo",
    },
]

FIELDS_BY_COLUMN = {f['column']: f for f in FIELDS}
FIELDS_BY_VARIABLE = {f['variable']: f for f in FIELDS}
